# Generated by Django 4.1.2 on 2022-11-02 20:45

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8a52c4a4-7ed0-423d-a3d2-3bf1e268aedc'), primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('image', models.CharField(max_length=200, verbose_name='Image')),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='CreatedAt')),
                ('updatedAt', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='UpdatedAt')),
                ('language', models.CharField(max_length=200, verbose_name='Language')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('53379c7a-b9a4-4dd5-9a68-8cc29606d2fa'), primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('average', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Average')),
                ('createdAt', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='CreatedAt')),
                ('updatedAt', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='UpdatedAt')),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
