# Generated by Django 4.1.2 on 2022-11-02 20:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ratingId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_movies.rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51f5aa47-9f0c-4492-b8b4-e976f2c2c090'), primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6d155844-4773-4356-9115-60da4c7b0994'), primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
    ]
