# Generated by Django 4.1.2 on 2022-11-02 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test_movies', '0003_movie_isdeleted_alter_movie_id_alter_movie_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fe52b1dc-15ea-496c-87d5-aeeda649d1b5'), primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bbd2cb4d-cf4f-44e2-9957-ed61074310fa'), primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='rating',
        ),
    ]
